services:
  - type: web
    name: cafeterias-api
    env: node
    plan: free
    region: oregon
    branch: main
    rootDir: .
    buildCommand: |
      corepack enable
      pnpm install --frozen-lockfile
      pnpm db:generate
    startCommand: pnpm start
    autoDeploy: true
    healthCheckPath: /health
    numInstances: 1
    runtime: node
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://cafeterias-api.onrender.com
      - key: REQUEST_BODY_LIMIT
        value: 15mb
      - key: UPLOAD_STRATEGY
        value: local
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_41GoEKCxzYbQ@ep-round-sky-a4s1pz5c-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        value: 6b3e97d7880698a40bcd1915377ebe6eb35d2f32d5987acf37e1e7a3a95cd10dd47644a8bcbd4f5a5db1ba46032dd5305265fd6a528c119a310bfb8c479b33ab
